### PR TITLE
Migrate everything to 3.9

### PR DESCRIPTION
**Pull request by simmel**
Homebrew has yet again done a upgrade which breaks everything.

So we must upgrade to 3.9 if we want anything to work at all. It's #35 et.al. all over again...

### CODE REVIEW

**Comment by jodal** [comment]
Looks good to me. Could you add `revision 1` where missing and bump to `revision 2` where `revision` is already specified, so that an upgrade is triggered for all users?

**Comment by simmel** [comment]
Done!

[Formula/libspotify.rb](https://github.com/mopidy/homebrew-mopidy/blob/master/Formula/libspotify.rb) contains no revision but I don't think it's necessary to force the users to reinstall it since it doesn't use anything related to Python when building?

**Comment by jodal** [comment]
> [Formula/libspotify.rb](https://github.com/mopidy/homebrew-mopidy/blob/master/Formula/libspotify.rb) contains no revision but I don't think it's necessary to force the users to reinstall it since it doesn't use anything related to Python when building?

That's correctly observed :-)

**Review by jodal — APPROVED** [review]

**Comment by jodal** [comment]
@simmel Thank you for helping with maintaining the formulas :-)

**Pull request merged**
